services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    volumes:
      - "./docker-data/pg:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_PROFILES_ACTIVE: dev
      CLUSTER_NAME: local-docker
      REGION: uk
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: changeme
    ports:
      - "${APP_HOST_PORT:-8080}:8080"
