spring:
  application:
    name: case-document-knowledge-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints.web.exposure.include: "health,info,metrics,prometheus,env,loggers,threaddump"
  endpoint.health.probes.enabled: true
  metrics:
    tags:
      service: case-document-knowledge-service
      cluster: ${CLUSTER_NAME:local}
      region: ${REGION:local}
  tracing:
    sampling.probability: ${TRACING_SAMPLER_PROBABILITY:1.0}
  otlp:
    tracing.endpoint: ${OTEL_TRACES_URL:http://localhost:4318/v1/traces}
    metrics:
      export:
        enabled: ${OTEL_METRICS_ENABLED:false}
        url: ${OTEL_METRICS_URL:http://localhost:4318/v1/metrics}

security:
  jwt:
    enabled: ${SECURITY_JWT_ENABLED:false}
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${OIDC_ISSUER_URI:}

springdoc:
  swagger-ui.path: /swagger-ui.html

logging:
  level:
    root: INFO
