apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: {{ include ".Chart.Name" . }}-pdb }
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include ".Chart.Name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
